<?php

/* Implementing hook_menu() */

function hide_menu_item_menu(){
  $items = array();
  $items['admin/structure/menu/hide_menu_item'] = array(
    'title'=>'Hide Menu Item',
    'description'=>'Hide Menu Item',
    'page callback'=>'hide_menu_item_config',
    'access callback'=>'user_access',
    'access arguments'=>array('administer access control'),
    'file'=>'hide_menu_item.settings_form.inc',
    );
  return $items;
}
